#!/usr/bin/env bash
set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m'
BLUE='\033[0;34m' BOLD='\033[1m' NC='\033[0m'

info()    { echo -e "${BLUE}▶${NC} $*"; }
success() { echo -e "${GREEN}✓${NC} $*"; }
warn()    { echo -e "${YELLOW}⚠${NC} $*"; }
error()   { echo -e "${RED}✗ ERROR:${NC} $*" >&2; exit 1; }

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}${BLUE}"
echo "  ███╗   ██╗██████╗     ███████╗██╗     ███████╗███████╗████████╗"
echo "  ████╗  ██║██╔══██╗    ██╔════╝██║     ██╔════╝██╔════╝╚══██╔══╝"
echo "  ██╔██╗ ██║██████╔╝    █████╗  ██║     █████╗  █████╗     ██║   "
echo "  ██║╚██╗██║██╔══██╗    ██╔══╝  ██║     ██╔══╝  ██╔══╝     ██║   "
echo "  ██║ ╚████║██║  ██║    ██║     ███████╗███████╗███████╗   ██║   "
echo "  ╚═╝  ╚═══╝╚═╝  ╚═╝    ╚═╝     ╚══════╝╚══════╝╚══════╝   ╚═╝   "
echo -e "${NC}${BOLD}                   Node-RED Fleet Manager${NC}"
echo ""

# When run as curl|bash, stdin is the pipe; switch to terminal for prompts
if [ ! -t 0 ] && [ -e /dev/tty ]; then
  exec 0</dev/tty
fi

# ── Check dependencies ────────────────────────────────────────────────────────
echo -e "${BOLD}[ 1/4 ] Checking dependencies...${NC}"

install_docker() {
  info "Running official Docker install script (https://get.docker.com)..."
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sudo sh /tmp/get-docker.sh
    rm -f /tmp/get-docker.sh
  else
    error "curl is required to install Docker. Install curl or Docker manually: https://docs.docker.com/get-docker/"
  fi
  # Start service on Linux if systemctl available
  if command -v systemctl >/dev/null 2>&1 && systemctl is-system-running &>/dev/null; then
    sudo systemctl start docker 2>/dev/null || true
    sudo systemctl enable docker 2>/dev/null || true
  fi
  warn "If Docker commands fail with 'permission denied', run: newgrp docker (or log out and back in), then run this script again."
}

if ! command -v docker >/dev/null 2>&1; then
  warn "Docker is not installed."
  echo -e "  Install it now? (runs official script: get.docker.com) [y/N]: \c"
  read -r INSTALL_DOCKER
  if [[ "${INSTALL_DOCKER:-n}" =~ ^[yY] ]]; then
    install_docker
  else
    error "Docker is required. Install it manually: https://docs.docker.com/get-docker/"
  fi
fi

if ! docker compose version >/dev/null 2>&1; then
  # After fresh install, Compose plugin may need a new shell or service start
  if command -v systemctl >/dev/null 2>&1; then
    sudo systemctl start docker 2>/dev/null || true
  fi
  if ! docker compose version >/dev/null 2>&1; then
    error "Docker Compose v2 not found. Install Docker Desktop or docker-compose-plugin: https://docs.docker.com/compose/install/"
  fi
fi

success "Docker: $(docker --version | grep -oP '\d+\.\d+\.\d+' || docker --version)"
success "Compose: $(docker compose version --short)"

# ── Clone repo if run via curl (no docker-compose in PWD) ───────────────────────
if [ ! -f docker-compose.yml ]; then
  command -v git >/dev/null 2>&1 || error "Git is required when installing via curl. Install git or clone the repo manually."
  INSTALL_DIR="$(pwd)/nr-fleet-manager"
  if [ -d "$INSTALL_DIR" ]; then
    warn "Directory $INSTALL_DIR already exists. Using it."
    cd "$INSTALL_DIR"
    git pull --quiet 2>/dev/null || true
  else
    info "Cloning repository into $INSTALL_DIR..."
    git clone --depth 1 https://github.com/lotockii/nr-fleet-manager.git "$INSTALL_DIR"
    cd "$INSTALL_DIR"
    success "Repository cloned"
  fi
fi

# ── Generate .env ─────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}[ 2/4 ] Generating configuration...${NC}"

if [ -f .env ]; then
  warn ".env already exists — skipping generation (delete .env to regenerate)"
else
  # Generate secrets
  gen_pass()   { openssl rand -base64 32 | tr -d '/+=\n' | head -c 24; }
  gen_secret() { openssl rand -hex 32; }

  DB_PASSWORD=$(gen_pass)
  JWT_SECRET=$(gen_secret)
  ADMIN_PASSWORD=$(gen_pass)
  SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")
  PORT="${PORT:-80}"

  cat > .env << EOF
# NR Fleet Manager — Auto-generated by install.sh
# $(date)

DB_NAME=nr_fleet
DB_USER=nr_fleet
DB_PASSWORD=${DB_PASSWORD}

JWT_SECRET=${JWT_SECRET}

ADMIN_EMAIL=admin@localhost
ADMIN_PASSWORD=${ADMIN_PASSWORD}

PORT=${PORT}
ALLOWED_ORIGINS=http://${SERVER_IP}:${PORT},http://localhost:${PORT}
NODE_ENV=production
EOF

  success ".env generated with random secrets"

  # Save credentials to file
  cat > .credentials << EOF
NR Fleet Manager — Initial Credentials
Generated: $(date)
========================================
URL:            http://${SERVER_IP}:${PORT}
Admin Email:    admin@localhost
Admin Password: ${ADMIN_PASSWORD}
========================================
IMPORTANT: Change password on first login!
Keep this file safe and delete after setup.
EOF

  success "Credentials saved to .credentials"
fi

# ── HTTPS Setup ───────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}[ 3/5 ] HTTPS / SSL (optional)${NC}"
echo -e "  If you have a domain pointing to this server, we can set up"
echo -e "  a free SSL certificate automatically via Let's Encrypt."
echo ""
read -rp "  Enter your domain (e.g. fleet.example.com) or press Enter to skip: " SSL_DOMAIN

HTTPS_ENABLED=false

if [ -n "${SSL_DOMAIN:-}" ]; then
  info "Setting up HTTPS for ${SSL_DOMAIN}..."

  # Install certbot if needed
  if ! command -v certbot >/dev/null 2>&1; then
    info "Installing certbot..."
    if command -v apt-get >/dev/null 2>&1; then
      apt-get install -y --quiet certbot 2>/dev/null \
        || snap install --classic certbot 2>/dev/null \
        || error "Could not install certbot. Install it manually: https://certbot.eff.org"
    elif command -v snap >/dev/null 2>&1; then
      snap install --classic certbot \
        || error "Could not install certbot via snap."
    else
      error "Cannot install certbot automatically. Please install it manually."
    fi
  fi

  # Make sure port 80 is free (stop frontend container if running)
  docker compose stop frontend 2>/dev/null || true
  sleep 1

  # Obtain certificate (standalone mode)
  ADMIN_EMAIL_VAL=$(grep '^ADMIN_EMAIL=' .env 2>/dev/null | cut -d= -f2 || echo "admin@${SSL_DOMAIN}")
  certbot certonly \
    --standalone \
    --non-interactive \
    --agree-tos \
    --email "${ADMIN_EMAIL_VAL}" \
    -d "${SSL_DOMAIN}" \
    || error "Failed to obtain SSL certificate. Make sure ${SSL_DOMAIN} points to this server's IP."

  CERT_PATH="/etc/letsencrypt/live/${SSL_DOMAIN}"
  success "SSL certificate obtained: ${CERT_PATH}"

  # Generate SSL nginx config
  cat > apps/dashboard/nginx-ssl.conf << NGINXEOF
# HTTP → HTTPS redirect
server {
    listen 80;
    server_name ${SSL_DOMAIN};
    return 301 https://\$host\$request_uri;
}

# HTTPS server
server {
    listen 443 ssl;
    server_name ${SSL_DOMAIN};
    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate     /etc/letsencrypt/live/${SSL_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${SSL_DOMAIN}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml application/json
               application/javascript application/xml+rss
               image/svg+xml;

    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Never cache index.html
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    # API proxy → backend
    location /api/ {
        proxy_pass http://backend:3001/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
    }

    # WebSocket proxy → backend
    location /ws {
        proxy_pass http://backend:3001/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # SPA fallback
    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
NGINXEOF
  success "SSL nginx config generated"

  # Update docker-compose.yml to add HTTPS port + cert volume to frontend
  # We use a docker-compose.override.yml so the base file stays clean
  cat > docker-compose.override.yml << OVERRIDEEOF
services:
  frontend:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./apps/dashboard/nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
OVERRIDEEOF
  success "docker-compose.override.yml created (HTTPS ports + cert volume)"

  # Update ALLOWED_ORIGINS in .env
  if grep -q '^ALLOWED_ORIGINS=' .env; then
    sed -i "s|^ALLOWED_ORIGINS=.*|ALLOWED_ORIGINS=https://${SSL_DOMAIN}|" .env
  else
    echo "ALLOWED_ORIGINS=https://${SSL_DOMAIN}" >> .env
  fi
  echo "DOMAIN=${SSL_DOMAIN}" >> .env

  # Set up auto-renewal cron (runs daily at 3:00 AM, restarts frontend after renewal)
  CRON_JOB="0 3 * * * certbot renew --quiet --deploy-hook 'cd $(pwd) && docker compose restart frontend' >> /var/log/certbot-renew.log 2>&1"
  ( crontab -l 2>/dev/null | grep -v "certbot renew"; echo "${CRON_JOB}" ) | crontab -
  success "Auto-renewal cron job set up (daily at 3:00 AM)"

  HTTPS_ENABLED=true
  success "HTTPS setup complete → https://${SSL_DOMAIN}"
else
  warn "Skipping HTTPS. App will be served over HTTP only."
  warn "For production, it is strongly recommended to configure HTTPS."
fi

# ── Build & Start ─────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}[ 4/5 ] Building and starting containers...${NC}"
info "This may take 3-5 minutes on first run (downloading images, building)..."
echo ""

docker compose up -d --build

# ── Wait for ready ────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}[ 5/5 ] Waiting for services...${NC}"

# Load PORT from .env
PORT_VAL=$(grep '^PORT=' .env 2>/dev/null | cut -d= -f2 || echo "80")

MAX_WAIT=90
WAITED=0
printf "  Checking backend"
until curl -sf "http://localhost:${PORT_VAL}/api/auth/login" \
    -X POST -H "Content-Type: application/json" \
    -d '{"email":"x","password":"x"}' \
    -o /dev/null 2>&1; do
  if [ $WAITED -ge $MAX_WAIT ]; then
    echo ""
    warn "Backend didn't respond in ${MAX_WAIT}s"
    warn "Check logs: docker compose logs backend"
    break
  fi
  printf "."
  sleep 3
  WAITED=$((WAITED + 3))
done
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
ADMIN_PASS_SHOW=$(grep '^ADMIN_PASSWORD=' .env 2>/dev/null | cut -d= -f2 || echo "(see .env)")
ADMIN_EMAIL_SHOW=$(grep '^ADMIN_EMAIL=' .env 2>/dev/null | cut -d= -f2 || echo "admin@localhost")
SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

if [ "${HTTPS_ENABLED}" = true ]; then
  APP_URL="https://${SSL_DOMAIN}"
else
  APP_URL="http://${SERVER_IP}:${PORT_VAL}"
fi

echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║         🎉  NR Fleet Manager is ready!               ║${NC}"
echo -e "${BOLD}${GREEN}╠══════════════════════════════════════════════════════╣${NC}"
echo -e "${BOLD}${GREEN}║${NC}  🌐 URL:       ${BOLD}${APP_URL}${NC}"
echo -e "${BOLD}${GREEN}║${NC}  📧 Email:     ${YELLOW}${ADMIN_EMAIL_SHOW}${NC}"
echo -e "${BOLD}${GREEN}║${NC}  🔑 Password:  ${YELLOW}${ADMIN_PASS_SHOW}${NC}"
echo -e "${BOLD}${GREEN}║${NC}"
echo -e "${BOLD}${GREEN}║${NC}  ⚠️  ${BOLD}Change password on first login!${NC}"
echo -e "${BOLD}${GREEN}╠══════════════════════════════════════════════════════╣${NC}"
echo -e "${BOLD}${GREEN}║${NC}  📋 Credentials also saved to: ${BLUE}.credentials${NC}"
echo -e "${BOLD}${GREEN}║${NC}"
if [ "${HTTPS_ENABLED}" = true ]; then
echo -e "${BOLD}${GREEN}║${NC}  🔒 HTTPS enabled — auto-renewal via cron (daily 3AM)"
echo -e "${BOLD}${GREEN}║${NC}"
else
echo -e "${BOLD}${GREEN}║${NC}  ⚠️  ${YELLOW}HTTP only — run install.sh again with a domain for HTTPS${NC}"
echo -e "${BOLD}${GREEN}║${NC}"
fi
echo -e "${BOLD}${GREEN}║${NC}  ${BLUE}docker compose logs -f${NC}          ← view logs"
echo -e "${BOLD}${GREEN}║${NC}  ${BLUE}docker compose down${NC}              ← stop"
echo -e "${BOLD}${GREEN}║${NC}  ${BLUE}docker compose down -v${NC}           ← stop + delete data"
echo -e "${BOLD}${GREEN}║${NC}  ${BLUE}git pull && bash install.sh${NC}      ← update"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
